spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gym
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true

  messages:
    basename: messages,errors

  thymeleaf:
    prefix: classpath:/templates/view/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    renewal.gym: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
  client:
    id : f_Cpy2Jv3A9Q0eD_xgnJ
    secret : 8FaOR6Nr2o

server:
  servlet:
    session:
      timeout: 30m