spring:
  config:
    import: "classpath:application-key.yml"

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/gym
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/gym_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true


  messages:
    basename: messages,errors

  thymeleaf:
    prefix: classpath:/templates/view/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    renewal.gym: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie

  error:
    whitelabel:
      enabled: false

file:
  dir: C:/Users/KDH/Pictures/upload/

