spring:
  config:
    import: "classpath:application-key.yml"

  datasource:
    url: jdbc:h2:tcp://localhost/~/gym
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true


  messages:
    basename: messages,errors

  thymeleaf:
    prefix: classpath:/templates/view/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    renewal.gym: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie

file:
  dir: C:/Users/KDH/Pictures/upload/